### ISSUE TITLE
Incorrect Errors on Unicode Characters 

### ISSUE THREAD

**Issue by cloudRoutine** [ionide/ionide-fsharp#108]
When I tried to declare a function using Σ in Atom it said the character was unexpected.

![2015-08-09_00-10-47](https://cloud.githubusercontent.com/assets/680051/9153540/7363f9a2-3e2b-11e5-9c1f-06547c831c94.png)
![2015-08-09_00-19-21](https://cloud.githubusercontent.com/assets/680051/9153555/53a1bef0-3e2c-11e5-8f3e-5dc85c3d6fdc.png)
( oddly the tooltips stop working during this error state, but the info bar continues to work )

However I know this character is supported as I've seen it in libraries in the past and visual studio gladly accepts it and even displays it inside tooltips.

![unquotefscheck_-_microsoft_visual_studio_2015-08-09_00-15-00](https://cloud.githubusercontent.com/assets/680051/9153546/bdd83570-3e2b-11e5-9570-817ba7ee9cce.png)

**Comment by tpetricek** [comment]
The fun thing is that (in Visual Studio), this works for uppercase sigma Σ, but not for n-ary summation  ∑ :-)

**Comment by Krzysztof-Cieslak** [comment]
Reported also in https://github.com/fsprojects/atom-fsharp/issues/34

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `1.3.0`
