### ISSUE TITLE
Support Build package

### ISSUE THREAD

**Issue by vasily-kirichenko** [ionide/ionide-fsharp#118]
https://github.com/noseglid/atom-build

**Comment by Krzysztof-Cieslak** [comment]
Is FAKE not enough? ;) 

Actually, I think that it should be reported in atom-build repository - looks like supported build tools like Rust's or Elixir's are implemented as part of its repository not in external plugins. 

Also it should be easy (?) to add MSBuild / FAKE build using their custom build stuff.

**Comment by vasily-kirichenko** [comment]
How I can launch FAKE from withing Atom? I cannot find it either in atom-fsharp readme nor in all the menus.

**Comment by Krzysztof-Cieslak** [comment]
`Ctrl + Shift + P` to open command palette and type in `FAKE` - there are few commands
`F5` to run default FAKE target.

However there are some assumptions - having *.cmd (or *.sh for Mono)  in root folder opened by Atom.

**Comment by baronfel** [comment]
just a thought: we could spin off the FAKE integration into a separate package, so that we could use the atom-build [service API](https://github.com/noseglid/atom-build#service-api-for-package-developers)? 

I'm intrigued by this, so I'll try to dig around some more.

**Comment by Krzysztof-Cieslak** [comment]
I'm planning to move FAKE to separate package with incoming organization changes (#96). 

Personally, I'm not sure about integration with atom-build - it's next dependency, and I kinda like current UX for FAKE. Anyway, If we update FAKE support to use atom-build, it won't happen before organization changes mentioned earlier - right now I'm mostly focused on fixing existing bugs and polishing user experience.

**Comment by Krzysztof-Cieslak** [comment]
FAKE support released and moved to separate plugin
