### ISSUE TITLE
FSI Doesn't Work on OS X

### ISSUE THREAD

**Issue by praeclarum** [ionide/ionide-fsharp#129]
I get the error:

> 'C:/Program Files (x86)/Microsoft SDKs/F#/4.0/Framework/v4.0/Fsi.exe' could not be spawned.
> Is it installed and on your path?
> If so please open an issue on the package spawning the process.

**Comment by Krzysztof-Cieslak** [comment]
In `ionide-fsi`plugin settings there is option to set path to FSI

**Comment by praeclarum** [comment]
Thanks!

For those who run into this:

> /usr/bin/fsharpi

works.
