### ISSUE TITLE
Basic types don't auto-complete

### ISSUE THREAD

**Issue by praeclarum** [ionide/ionide-fsharp#131]
`int` and `string` in particular

This makes typing very difficult as it's always auto-completing to some random class name.

**Comment by Krzysztof-Cieslak** [comment]
I don't think I understand problem. Can You provide code sample and / or GIF from what You try to do?

**Comment by cloudRoutine** [comment]
@praeclarum  I think you might be having an issue that I used to before I changed my autocompletion settings. In the core package `autocomplete-plus` you can disable show suggestions on keystroke. 

`int` and `string` do show up in the completion list, but the ordering could definitely be improved. I'll see what I can do to improve it.

If I misunderstood your issue, please elaborate further about the nature of the problem.

**Comment by Krzysztof-Cieslak** [comment]
Fixed by introducing ordering in version `1.1.1`
