### ISSUE TITLE
Cannot find FAKE script

### ISSUE THREAD

**Issue by devshorts** [ionide/ionide-fsharp#132]
I'm on a mac and trying to test out FAKE integration. I have a build.fsx file at the root of my project and FAKE installed with paket.  The fake binaries are there and when run from the command line:

```
 mono packages/FAKE/tools/FAKE.exe build.fsx
```

It all works great. However in the editor I get

![image](https://cloud.githubusercontent.com/assets/1799346/9977932/63e8b0bc-5ece-11e5-90c5-ee7dd75093ec.png)

Here is a screenshot of my project structure 

![image](https://cloud.githubusercontent.com/assets/1799346/9977933/7fcd14da-5ece-11e5-8ef2-95c698f30752.png)

**Comment by Krzysztof-Cieslak** [comment]
Read.me is definitely lacking some information there.

FAKE plugin is expecting You to have `*.cmd` (or `*.sh` for mono) file in root folder opened by Atom. In this file You execute FAKE with build script as parameter - I know that those are some serious assumptions but that's how most user uses it (and I'm currently working on some way to customize it). You can check almost any OSS F# project for examples how it's used (for example `Ionide` repos :wink: on develop branch or ProjectScaffold setup )

**Comment by devshorts** [comment]
Cool I'll give that a shot. Haven't played much with fake or paket so thanks for pointing me in the right direction!

**Comment by blair55** [comment]
> I'm currently working on some way to customize it

@Krzysztof-Cieslak Any progress with this?

**Comment by Krzysztof-Cieslak** [comment]
@blair55 https://github.com/ionide/ionide-fake#configuration

**Comment by blair55** [comment]
@Krzysztof-Cieslak nice, thanks!
