### ISSUE TITLE
"paket.bootstrapper.exe could not be spawned"?

### ISSUE THREAD

**Issue by darrix** [ionide/ionide-fsharp#138]
Hi, I've installed the package through Atom settings and I'm receiving a message saying that the "paket.bootstrapper.exe could not be spawned".  Is there something else I need to load?  I've tried uninstalling and then re-installing with the same result.  Running on Windows 10.

**Comment by Krzysztof-Cieslak** [comment]
Hey, can You check if You can run `paket.bootstrapper.exe` file manually. It should be located in `C:\Users\USERNAME\.atom\packages\ionide-paket\bin`

**Comment by darrix** [comment]
Yes, I was able to run it there.  I am noticing now however that the the path referred to in the error message is "C:\Users\USERNAME.atom\packages/ionide-paket/bin/paket.bootstrapper.exe", with no slash separating the username from the '.atom' directory.

**Comment by sergey-tihon** [comment]
The same issue
![image](https://cloud.githubusercontent.com/assets/1197905/10148070/353b8492-663a-11e5-9e1a-7bffe4d55aea.png)

**Comment by Krzysztof-Cieslak** [comment]
Issue discussed here - https://github.com/ionide/ionide-paket/issues/20
