### ISSUE TITLE
'fsharpi' could not be spawned on OS X

### ISSUE THREAD

**Issue by mcgee** [ionide/ionide-fsharp#140]
I have mono installed via homebrew. If I try to call ``fsharpi`` via terminal it works correctly. However, if I do this via atom ``FSI: Open`` open command it throws ```'fsharpi' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.```

**Comment by Krzysztof-Cieslak** [comment]
In `ionide-fsi` package settings there is place to setting up FSI path. Try setting it manually.

**Comment by mcgee** [comment]
Thanks, that helped. I've set this setting to ``/usr/local/bin/fsharpi``

**Comment by jeremyabbott** [comment]
I set my FSI path to /usr/local/bin/fsharpi as suggested above, and now I encounter the following error:

`/usr/local/bin/fsharpi: line 24: exec: mono: not found`

If I set the path to `/usr/local/bin` I don't get an error, but I don't see any output in the F# Interactive pane either. However I know fsharpi is symlinked to /usr/local/bin. 

Do you guys have any suggestions?

**Comment by Krzysztof-Cieslak** [comment]
Maybe try setting `fsharpi` path to `/usr/local/bin/fsharpi` and `mono` path to right path in `ionide-fsharp` settings

**Comment by jeremyabbott** [comment]
Thanks for getting back to me!

I'm not sure what you mean by  "`mono` path to right path..." Here's where mono and fsharpi exist on $PATH (OS X, El Capitan):
![screen shot 2015-11-03 at 8 58 36 pm](https://cloud.githubusercontent.com/assets/991806/10928413/d3a33a40-826d-11e5-973d-45cc2a8e2c90.png)

Here's how ionide-fsharp is configured:
![screen shot 2015-11-03 at 9 00 28 pm](https://cloud.githubusercontent.com/assets/991806/10928448/ff5d2ce0-826d-11e5-91b5-6aaff57e8261.png)

Here's how ionide-fsi is configured:
![screen shot 2015-11-03 at 9 00 42 pm](https://cloud.githubusercontent.com/assets/991806/10928456/14253f14-826e-11e5-841d-2cb0ae0a569c.png)

Thank you again for the help. I'm sure it's something I'm doing wrong.

**Comment by Krzysztof-Cieslak** [comment]
@jeremyabbott, well it looks OK. You can check #128 for more discussion and possible solutions for `mono` spawn problem.

**Comment by jeremyabbott** [comment]
Yeah. Opening atom from the command line fixed my problem. I'm going to blog about my heart-ache ;). Hopefully it will help others. Thank you again for your help.

**Comment by zellus** [comment]
Unable to spawn fsharpi ... ionide-fsi 1.0.9, Atom 1.2.4, and OSX 10.11.1
