### ISSUE TITLE
Autocomplete results that require backtick encapsulation do not receive it

### ISSUE THREAD

**Issue by willryan** [ionide/ionide-fsharp#142]
When an identifier requires backtick encapsulation (as is often the case with fields from type providers), autocomplete will show the result but will not supply the backticks when a result is selected.  So the resulting code is in an invalid state until you go in and insert the backticks.  Visual Studio and Xamarin Studio both properly insert the backticks for you, but ionide does not.  I think you could fix it pretty easily by updating this section of Autocomplete.fs (which is basically repeated in two cases):

|> Seq.map(fun t -> { text = t.Name
                                  replacementPrefix = prefix
                                  rightLabel = t.Glyph
                                  ``type`` = t.GlyphChar
                                 } :> obj)

Suggestion.text would need to be translated to include backticks if t.Name is not a valid identifier.  Technically backtick encapsulation should also be applied for field results that are F# keywords, but the main pain point is handling "invalid" characters (particularly space and square braces).  Also, if you want to avoid showing the backticks in the suggestion dropdown, I think you can add a field Suggestion.displayText, and Atom will use the 'displayText' in in the suggestion but replace it with 'text'.

You could make an argument that the fix should happen in FsAutoComplete, as it is also an issue with the F# vim plugin and possibly others (I haven't checked emacs or sublime).  However it might be safest to do the checking here regardless.

**Comment by cloudRoutine** [comment]
Sounds good, thanks for the suggestion.

**Comment by willryan** [comment]
I did a bit more digging and found 

```Microsoft.FSharp.Compiler.SourceCodeServices.PrettyNaming.QuoteIdentifierIfNeeded```

which I think will do precisely what is needed here.  It was very recently made publicly accessible.

**Comment by Krzysztof-Cieslak** [comment]
Cool, thanks for this suggestion. If we wanted to use `Microsoft.FSharp.Compiler.SourceCodeServices.PrettyNaming.QuoteIdentifierIfNeeded` change would need to be done in FsAutoComplete ( as we don't have direct access to Compiler Services from Atom). If we want to put checking on Atom side we will need to code own our logic for that.

**Comment by willryan** [comment]
Ah, ok.  We don't have access to FCS because ionide is written in FunScript compiling to Javascript, am I understanding that correctly?  Anyway, I guess the source to QuoteIdentifierIfNeeded could still be valuable as a reference if you make a fix in ionide.

**Comment by rneatherway** [comment]
I add the backticks myself in the emacs support. I can't remember why I didn't end up doing it in FsAutoComplete, perhaps it would belong better there.

**Comment by Krzysztof-Cieslak** [comment]
Solved by updating to new FSAC.
