### ISSUE TITLE
Coloring is off when using intl. characters

### ISSUE THREAD

**Issue by rojepp** [ionide/ionide-fsharp#150]
I *think* this is the right repo to report this to. :)

<img width="302" alt="screenshot 2015-09-30 23 24 33" src="https://cloud.githubusercontent.com/assets/445888/10207092/97def9f8-67ca-11e5-8240-ea351ee7d3fd.png">

The variables `bedömningsId` and `värdeTyp` in the screenshot should be all red. Probably an `[a-zA-Z]` somewhere, I haven't looked at it yet.

**Comment by cloudRoutine** [comment]
Updated the regex for these cases,  
![](http://i.imgur.com/zP90kzd.png)
I need to go through the rest of it to find some other mistakes.
This fix and some other highlighting fix will be in the next release.

**Comment by rojepp** [comment]
Awesome, thanks!
