### ISSUE TITLE
'/usr/bin/mono' could not be spawned.

### ISSUE THREAD

**Issue by palutz** [ionide/ionide-fsharp#151]
I've got this error message when installing and every time running Atom on my Mac OS X:
'/usr/bin/mono' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

Mono is installed but in another path: /usr/local/bin/mono
but running properly and included in the PATH setting.
This is the result of this command
$ mono -V
Mono JIT compiler version 4.2.0 (Stable 4.2.0.179/a224653 Fri Aug 28 13:53:46 PDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com

what am I missing?

Thanks in advance for any help.

/Stefano

**Comment by carsten-j** [comment]
I have the exact same setup and I see the exact same error. Any feedback is highly appreciated.
Carsten

**Comment by railcar88** [comment]
Try this: go to Settings > choose Install > Search for ionide-fsharp under Install Packages > click on the Settings button of the ionide-fsharp package > scroll down to the Mono Path setting > change it from: /usr/bin to: usr/local/bin > close Atom > open Atom
![screenshot_2015-10-01_16-17-52](https://cloud.githubusercontent.com/assets/6291128/10232651/ffdd9de2-6857-11e5-974a-90ec2f5255e6.png)

**Comment by carsten-j** [comment]
Thanks but that did not really change anything. Now I just get this error message instead
![screenshot 2015-10-01 22 22 25](https://cloud.githubusercontent.com/assets/2677833/10232794/0c7d74f4-688b-11e5-891d-5752b6674aa8.png)

**Comment by palutz** [comment]
Exactly the same for me. Same error, same message.
I think it's worth mentioning I installed Mono using brew.

**Comment by Krzysztof-Cieslak** [comment]
Problem discussed also in #128. Please move discussion there and check it out for possible solutions.
