### ISSUE TITLE
Fails on osx El Capitan, you cannot depend on `mono` being in the path is system protection is enabled.

### ISSUE THREAD

**Issue by 7sharp9** [ionide/ionide-fsharp#155]

**Comment by lilred** [comment]
Can you elaborate on this "system protection" thing? Most of us here are unfamiliar with OS X internals, but I have access to an OS X machine and with your help I could probably track down this issue.

**Comment by 7sharp9** [comment]
If system protection is turned on then applications do not have access to the path variable so anything like `mono myapp.exe` will fail if run within another application.  From the terminal it will work ok though.

**Comment by jimmydburr** [comment]
Confirmed here. I can type 'atom' in the terminal and the program executes fine, i.e. no warnings or errors. On the other hand, running Atom by double-clicking the icon results in a big red 'mono' could not be spawned error notification.

BTW, thank you @7sharp9 for figuring out the problem. I was going crazy trying to track it down.

**Comment by stweb** [comment]
http://www.macworld.com/article/2948140/os-x/private-i-el-capitans-system-integrity-protection-will-shift-utilities-functions.html

**Comment by Krzysztof-Cieslak** [comment]
It's not only El Capitan problem - issue described in #128. Please move discussion there
