### ISSUE TITLE
linter/intellisense not working

### ISSUE THREAD

**Issue by isamuelson** [ionide/ionide-fsharp#156]
i don't get the linter functionality nor the intellisense

**Comment by lilred** [comment]
Thanks for the report! Can you elaborate a bit? In particular,

* What operating system are you using?

* What versions of Atom and Ionide are you using?

* Did it stop working while you were using it, or did you open the editor and it was already not working? Do you remember it ever working?

Best

**Comment by isamuelson** [comment]
OS: OSX El Capitan 
Atom ver: 1.0.19

it is a new installation of atom + ionide , never worked...

**Comment by theodorecackowski** [comment]
Same manifestation, same circumstances, perhaps different cause.
When opening in 'developer mode' I get the following:
    'C:\Users\tcackowski\.atom\dev\packages/ionide-fsharp/bin/fsautocomplete.exe' 
    could not be spawned. Is it installed and on your path? 
    If so please open an issue on the package spawning the process.
But there is no .atom/dev/ directory, only .atom/packages,
I will try simply putting it there myself.
Adding to my user path didn't help.

**Comment by theodorecackowski** [comment]
Nevermind. 
I had disabled autocomplete-plus, a core package, because of a previous conflict.
I re-enabled it.
Also, one just has to wait a while for the autocomplete provider to load (~15 seconds)
Also, after just guessing from having used VS for so long, 
Ctrl+Space seems to stimulate the auto completer.
So maybe there should be, on the ionide-sharp settings, a list of auto-complete stimulating characters, like '.,->,(,=' or so?

**Comment by Krzysztof-Cieslak** [comment]
@isamuelson, Do You get any error notification? Can You open Developer console (View |> Developer |> Toggle Developer Tools) and check if there is any error logging here?

@theodorecackowski, We are aware that documentation is almost not existing and making it better is our next short term goal :)

**Comment by isamuelson** [comment]
no errors when I open atom from a directory

**Comment by Vxsery** [comment]
Getting the following in dev mode:
>'C:\Users\Jorge.atom\dev\packages\ionide-paket\bin\paket.bootstrapper.exe' could not be spawned.
>Is it installed and on your path?
>If so please open an issue on the package spawning the process.
