### ISSUE TITLE
not loading references - intelisense

### ISSUE THREAD

**Issue by isamuelson** [ionide/ionide-fsharp#158]
I added a reference (using paket) 

intelisense does not seem to load the references from the fsproj file

**Comment by Krzysztof-Cieslak** [comment]
Can You provide sample `fsproj` and `fs` file to reproduce issue?

**Comment by takemyoxygen** [comment]
I actually have similar problem. I see
**"The namespace or module 'Suave' is not defined at..."**
when opening Suave module in fs file (e.g. myfile.fs) that is not included in the fsproj. After I manually add
```
<Compile Include="myfile.fs" />
```
to my fsproj file, the error disappears. Is it an expected behavior?

**Comment by Krzysztof-Cieslak** [comment]
@takemyoxygen, Yes. it's expected behavior - `.fs` files need to be added to `.fsproject` file to know about references.
