### ISSUE TITLE
Add small delay on error highlighting

### ISSUE THREAD

**Issue by lilred** [ionide/ionide-fsharp#160]
User experience issue: when writing F# code in Ionide, error messages keep flashing at me and instantly disappearing. This is because Ionide will eagerly detect and report errors even as I'm in the middle of typing.

This is a matter of personal taste, but I like Visual Studio's approach for this: there's a ~0.5s delay between the moment I stop typing and the moment any new errors are reported.

Thoughts?

**Comment by Krzysztof-Cieslak** [comment]
Unfortunately, we don't have control over it as we just provide service implementation for [linter plugin](https://github.com/atom-community/linter)

**Comment by lilred** [comment]
Understood. I'll open an issue with the linter repo.

**Comment by lilred** [comment]
Turns out that the linter plugin does expose this functionality - see atom-community/linter#952. On the other hand, it's a global setting (i.e. it affects more than just Ionide), so it might not be a good idea to tweak it.

**Comment by lilred** [comment]
There's some action going on in the linter repo (see atom-community/linter#952). Once their PR hits production, we'll be able to solve this issue without much trouble.

**Comment by Krzysztof-Cieslak** [comment]
I don't think we need to have this issue open (unless they decide to implement per-plugin settings, but it doesn't look like this from current discussion). When they implement feature, you will be just able to set delay as you want.

**Comment by steelbrain** [comment]
Be advised, this has been fixed in linter.
