### ISSUE TITLE
Enabling ionide-fsharp breaks the "close pane" command

### ISSUE THREAD

**Issue by berdario** [ionide/ionide-fsharp#161]
demo:

https://www.youtube.com/watch?v=lrST0g_vD9Q

**Comment by Krzysztof-Cieslak** [comment]
Thanks for such nice report. I've also experienced that bug, but wasn't thinking that it might be connected with our plugin.

**Comment by berdario** [comment]
The tool that I used to pinpoint ionide-fsharp is [package-cop](https://atom.io/packages/package-cop) if you're interested

**Comment by cloudRoutine** [comment]
package-cop is just what I needed, thanks for the tip

**Comment by dcolthorp** [comment]
+1! Any news on this bug? As someone coming from vim who splits constantly, this is extremely frustrating. I'm currently resorting to toggling this plugin and restarting Atom on a regular basis as I bounce between F# and other languages.

**Comment by berdario** [comment]
I think I noticed a different behavior with the latest versions of Atom. The bug is still here, but after failing to close a pane, if you open another one and then try to close it again, the command seems to work again.

I don't remember this being the case with previous Atom versions

**Comment by Krzysztof-Cieslak** [comment]
Hopefully, at last, fixed in `1.6.2`.
