### ISSUE TITLE
Overeager autocomplete: carriage returns

### ISSUE THREAD

**Issue by lilred** [ionide/ionide-fsharp#164]
This could easily be a problem with Atom, but usually when hitting return I don't want to replace something, I just want a newline.

**Comment by Krzysztof-Cieslak** [comment]
Not sure if I understand right what's the problem, but let's try.

In `autocomplete-plus` plugin in Atom there is option to choose `Keymap for confirming suggestions` - where possible options are `tab`, `enter`, `enter and tab`. I would suggest using just `tab` - both for this issue, and as workaround for #162 and #163

**Comment by lilred** [comment]
Right now, mine is set to `tab and enter` (default), but the problem is there regardless.
