### ISSUE TITLE
Ubuntu 14.04: "Cannot open assembly '$HOME/.atom/packages/ionide-fsharp/bin/fsautocomplete.suave.exe': No such file or directory."

### ISSUE THREAD

**Issue by lilred** [ionide/ionide-fsharp#168]
![screenshot from 2015-10-21 17 56 57](https://cloud.githubusercontent.com/assets/1834919/10651376/23f10afa-781d-11e5-9d6a-6f3bac100ac8.png)

**Comment by Krzysztof-Cieslak** [comment]
Can You confirm if this file really doesn't exist? If so it might be some problem with installation, I'd try reinstalling plugin.

**Comment by radekm** [comment]
In my installation this file did not exist, instead there was a file `FsAutoComplete.Suave.exe`. I solved it by `cp FsAutoComplete.Suave.exe fsautocomplete.suave.exe`.

**Comment by rmunn** [comment]
This has probably been fixed by 7be25a9, which is part of the just-released version 1.4.2. Try running `apm update` to get 1.4.2 and see if that fixes the problem.

**Comment by Krzysztof-Cieslak** [comment]
Yes, it should be also fixed in `1.4.2`
