### ISSUE TITLE
The plugin is not functioning after updating to 1.4 

### ISSUE THREAD

**Issue by zhengbli** [ionide/ionide-fsharp#169]
The error message I got：
![error](https://cloud.githubusercontent.com/assets/1171301/10657536/d04e415e-7841-11e5-93f9-e61032cce518.PNG)

Side note: I can run fsi from powershell fine, so F# is installed on my machine.

Things I've tried:
1. install the latest release from https://github.com/Microsoft/visualfsharp/releases
2. reinstall visual studio
3. reinstall atom and ionide installer

**Comment by zhengbli** [comment]
This issue is solved after installing Visual F# Tools 3.1.2 from http://www.microsoft.com/en-us/download/details.aspx?id=44011

Maybe this should be added to the prerequisite?

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `1.4.2`
