### ISSUE TITLE
Uncaught TypeError: editor.displayBuffer.getScrollTop is not a function

### ISSUE THREAD

**Issue by zhengbli** [ionide/ionide-fsharp#170]
This happens with normal intellisense query after `.`

**Atom Version**: 1.1.0-beta1
**System**: Microsoft Windows 10 Pro
**Thrown From**: [ionide-fsharp](https://github.com/ionide/ionide-fsharp) package, v1.4.0

### Stack Trace

Uncaught TypeError: editor.displayBuffer.getScrollTop is not a function

```
At C:\Users\lizhe\.atom\packages\ionide-fsharp\lib\fsharp.js:5294

TypeError: editor.displayBuffer.getScrollTop is not a function
  at C:\Users\lizhe\.atom\packages\ionide-fsharp\lib\fsharp.js:5294:48
  at ViewsHelpers__bufferPositionFromMouseEvent$ (C:\Users\lizhe\.atom\packages\ionide-fsharp\lib\fsharp.js:5299:7)
  at TooltipHandler__getPosition$ (C:\Users\lizhe\.atom\packages\ionide-fsharp\lib\fsharp.js:4936:20)
  at HTMLDivElement.<anonymous> (C:\Users\lizhe\.atom\packages\ionide-fsharp\lib\fsharp.js:5069:19)
  at HTMLDivElement.jQuery.event.dispatch (C:\Users\lizhe\.atom\packages\ionide-fake\node_modules\jquery\dist\jquery.js:4430:9)
  at HTMLDivElement.elemData.handle (C:\Users\lizhe\.atom\packages\ionide-fake\node_modules\jquery\dist\jquery.js:4116:28)

```

### Commands

```
     -0:04.7.0 application:open-file (div.pane-item.native-key-bindings.about)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
ionide-fake, v1.2.0
ionide-fsharp, v1.4.0
ionide-fsi, v1.0.8
ionide-installer, v1.3.0
ionide-paket, v2.2.0
ionide-webview, v1.0.0
ionide-yeoman, v1.0.1
linter, v1.8.1

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment]
It might be some problem (and Atom API change) in beta version, I've not tested it yet on beta channel, and our plugin doesn't support it yet.

**Comment by zhengbli** [comment]
Actually now atom 1.1 is out, the issue exists in 1.1 too. So reopening it.

**Comment by sandorr** [comment]
You have to use `editor.getScrollTop()` instead of `editor.displayBuffer.getScrollTop()` in the definiton of `bufferPositionFromMouseEvent`, because `getScrollTop` has moved from `DisplayBuffer` to `TextEditorElement` since atom/atom@535a9da94657f92498f8bc7f3f27c07c779555d6.

**Comment by forki** [comment]
Atom is going crazy with this exception

**Comment by reidev275** [comment]
Yep, Looks like it's on mouse move after mouse idle for me

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in 1.4.4

**Comment by forki** [comment]
Thanks buddy. Will try tomorrow.

**Comment by CannellePlus** [comment]
I have the same issue here with 1.4.5
