### ISSUE TITLE
no autocomplete support in v1.4.5 

### ISSUE THREAD

**Issue by s-trooper** [ionide/ionide-fsharp#176]
i never got auto complete support in iodide even not in latest v1.4.5 .

I would like to ask: are there ppl with non English Windows version? as i have German version of .NET and F# 4.+ (VS2015) combination that got auto completion working in atom?

v1.4.5  error:
```
{"Kind":"error","Data":"Could not load file or assembly 'Microsoft.Build.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Das System kann die angegebene Datei nicht finden."}
```

**Comment by Krzysztof-Cieslak** [comment]
cc: @rneatherway FSAC problem?

**Comment by rneatherway** [comment]
@Krzysztof-Cieslak is this using the Suave backend? If you haven't added the ResolveEventHandler like in the pipe version (https://github.com/rneatherway/FsAutoComplete/blob/master/FsAutoComplete.Core/CompilerServiceInterface.fs#L164) that's probably the issue.

**Comment by Krzysztof-Cieslak** [comment]
Yeah, that's probably it. Thanks.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `1.4.6`

**Comment by s-trooper** [comment]
not real as 1.4.7 regressed to https://github.com/ionide/ionide-fsharp/issues/171 can this or 171 be reopen for one may find the solution eventually?

**Comment by s-trooper** [comment]
ok, i got auto completion with FSAC master working! i have had to add MSBuild dependencies from "FSharp.Compiler.Tools/4.0.0.1" to the "ionide-fsharp\bin" directory. 

```
Microsoft.Build.dll
Microsoft.Build.Engine.dll
Microsoft.Build.Framework.dll
```

Its not the solution for the https://github.com/ionide/ionide-fsharp/issues/171 as there is "wrong" F# 3.0 FSharp.Core.dll but for v1.4.5? sure for master version of fsautocomplete.

**Comment by Krzysztof-Cieslak** [comment]
Can You try using `1.4.9` ?

**Comment by s-trooper** [comment]
You are my hero !!! great thanks, its work (1.4.9)! Now i will go play with it ...

P.S: i close the issue.

**Comment by ReverseBlade** [comment]
I started to have this issue again starting 1.7.0 suddenly  . The weird thing is it only happens on one of my machines only.
