### ISSUE TITLE
'FsAutoComplete.Suave.exe' could not be spawned

### ISSUE THREAD

**Issue by dsyme** [ionide/ionide-fsharp#178]
I upgraded to 1.4.7 and get this on startup:

    'C:\Users\dsyme.atom\packages/ionide-fsharp/bin/FsAutoComplete.Suave.exe' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

This is on windows

**Comment by dsyme** [comment]
Missing \, should be 

     C:\Users\dsyme\.atom\packages/ionide-fsharp/bin/FsAutoComplete.Suave.exe

**Comment by Krzysztof-Cieslak** [comment]
Can You open developer console (`ctrl + alt+ i` or `view |> Developer |> Toggle Developer Tools`) and check out if there are any more details on error logged there?

**Comment by dsyme** [comment]
Uncaught Error: spawn C:\Users\dsyme\.atom\packages/ionide-fsharp/bin/FsAutoComplete.Suave.exe ENOENT

**Comment by Krzysztof-Cieslak** [comment]
Hmm, that's not really helpful. Can You start `C:\Users\dsyme\.atom\packages/ionide-fsharp/bin/FsAutoComplete.Suave.exe` from command line?

**Comment by dsyme** [comment]
yes

    C:\GitHub\dsyme\visualfsharp> C:\Users\dsyme\.atom\packages/ionide-fsharp/bin/FsAutoComplete.Suave.exe
    [I] 2015-11-10T22:42:35.3580950Z: listener started in 19.013 ms with binding 127
.0.0.1:8088 [Suave.Tcp.tcpIpServer]

**Comment by alaurie** [comment]
I have the exact same issue.

**Comment by Krzysztof-Cieslak** [comment]
Can you try latest update (`1.4.8`) ?

**Comment by dsyme** [comment]
Still not working.  [This code](https://github.com/ionide/ionide-fsharp/blob/05fd8de6959061bdc3418d8a29357248d0eea440/src/Core/LanguageService.fs#L153) looks wrong for windows - it's kind of all over the place.  It mentions "mono" but we don't want to use that. 


I also looked at the decompiled JS code for Process.spawn and it looks wrong - at least I couldn't really see how it made sense - do you know where that's defined?

**Comment by Krzysztof-Cieslak** [comment]
`Process.spawn` is my function (defined https://github.com/ionide/ionide-helpers/blob/master/src/ProcessHelpers.fs#L69-L77) - it's just checking if process is running on windows or linux/mac and fires node spawn functions with appropriate arguments. I think problem is somewhere else - it has not be changed in last few months.

**Comment by dsyme** [comment]
I think it's the ``cwd`` argument in the options to Process.spawn.  When I change

    var options = (new Options___ctor$((((window.atom).project).getPaths())[0]));

to 

    var options = (new Options___ctor$("c:\\misc"));

in the JS code for ``Process__spawn$`` it starts ok.  So I presume `` Globals.atom.project.getPaths().[0]`` is not a valid directory or somehow problematic when I open Atom.

**Comment by Krzysztof-Cieslak** [comment]
Does your Atom start without any folder opened? Usually it starts with same folder that was opened in last session. But I guess it should be fixed anyway, will make new release soon.

**Comment by dsyme** [comment]
It's starting with a couple of folders open.  I don't think there's anything particularly odd about them though

**Comment by dsyme** [comment]
Oh, the first folder open is the "config" folder for managing atom configuration - it's not a real folder.  Perhaps that's the problem.

**Comment by dsyme** [comment]
Yes, when I remove that as a project folder the problem goes away.  (it appeared as a project folder when I went to upgrade ionide :) )

**Comment by Krzysztof-Cieslak** [comment]
Cool, I'm glad it's working. I will close issue when I fix this problem, should be easy knowing how to reproduce it :)

**Comment by Krzysztof-Cieslak** [comment]
Fixed in 1.4.12
