### ISSUE TITLE
Problem spawning FSI

### ISSUE THREAD

**Issue by darrix** [ionide/ionide-fsharp#179]
Hi, I'm getting an error "'C:/Program Files (x86)/Microsoft SDKs/F#/4.0/Framework/v4.0/Fsi.exe' could not be spawned." The detailed error begins with "Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.  (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference."  

Now, FSI.exe is installed in that location and it's the version that's installed with VS2015.  

I do have the 1.4.8 plugin installed and I'm running the 1.2.0 version of Atom.

Ideas?  What should I check?

**Comment by cloudRoutine** [comment]
Try installing http://www.microsoft.com/en-us/download/details.aspx?id=44011
