### ISSUE TITLE
Ionide could not spawn processes

### ISSUE THREAD

**Issue by sergey-tihon** [ionide/ionide-fsharp#180]
Errors:
>Uncaught Error: spawn C:\Users\Sergey_Tihon\.atom\packages\ionide-fsharp\bin\FsAutoComplete.Suave.exe ENOENT
>events.js:141 Uncaught Error: spawn C:\Users\Sergey_Tihon\.atom\packages\ionide-paket\bin\paket.bootstrapper.exe ENOENT

These errors occurs for a couple of month:
-  Ionide never worked on my machine (even on `Win 8.1`).
- I have tried to restart, reinstall and update to newer versions many times.
- All `.exe` files exist on my machine and I am able to run them manually.
- The same behavior even when Symantec is turned off.

Current OS: `Windows 10 Enterprise 64 bit`

![image](https://cloud.githubusercontent.com/assets/1197905/11142330/8455333e-89fd-11e5-9967-c1b508e10ec7.png)

**Comment by Krzysztof-Cieslak** [comment]
It might be connected with #178. Can You try opening any folder with Atom and restarting it?

**Comment by sergey-tihon** [comment]
It seems that you are right,  it is much better with the open folder!
![image](https://cloud.githubusercontent.com/assets/1197905/11142748/c6cd9c9e-8a00-11e5-9cce-c525a7829c78.png)

**Comment by Krzysztof-Cieslak** [comment]
Can You try `1.4.9` ?

**Comment by sergey-tihon** [comment]
Wow, awesome! No error in the console!
Now I need to understand how to work in Atom)
Thank you!
