### ISSUE TITLE
'/usr/bin/mono' could not be spawned error during install (installer use wrong path to mono)

### ISSUE THREAD

**Issue by mmc41** [ionide/ionide-fsharp#183]
When trying to run ionide-installer in latest atom on OS X 10.10 I get the error '/usr/bin/mono' could not be spawned. I have mono 4.2.1 installed but the path is not as ionide-installer thinks but on "/usr/local/bin/mono" instead.

**Comment by Adron** [comment]
I just got the same, as the latest mono/Xamarin installer puts mono at '/usr/local/bin/mono'.

**Comment by Adron** [comment]
Was just looking at the code here in main.fs:

        yield "config:  {
            ShowQuickInfoPanel: {type: 'boolean', 'default': true},
            ShowUseHighlights: {type: 'boolean', 'default': true},
            DeveloperMode: {type: 'boolean', 'default': false},
            MonoPath: {type: 'string', 'default': '/usr/local/bin'},"

I was thinking of adding some *.json file and submitting a PR for it. Would that be something that would be usable or are we attempting to avoid a *.json config (or other type of) file? What do you think @Krzysztof-Cieslak @forki @tpetricek @cloudRoutine & crew?
