### ISSUE TITLE
autocomplete isn't working on osx

### ISSUE THREAD

**Issue by naveensrinivasan** [ionide/ionide-fsharp#188]
On OSX the auto complete isn't working. 

I had trouble with mono path and I have it all figured out. 

Here is my config.cson

```
"*":
  "exception-reporting":
    userId: "afc9990f-0ece-daa0-b4d2-5a618d6dabb3"
  welcome:
    showOnStartup: false
  "ionide-fsi":
    FsiPath: "/usr/local/bin/fsharpi"
  core:
    disabledPackages: [
      "vim-mode"
    ]
  editor:
    invisibles: {}
  "ionide-paket":
    MonoPath: "/usr/local/bin"
  "ionide-fsharp":
    MonoPath: "/usr/local/bin"
    FormatDocument:
      IndentOnTryWith: true
      ReorderOpenDeclaration: true
      StrictMode: true
    DeveloperMode: true
  "vim-mode":
    useClipboardAsDefaultRegister: true
    useSmartcaseForSearch: true
  "autocomplete-plus": {}
```
<img width="1138" alt="screen shot 2015-12-26 at 9 14 58 pm" src="https://cloud.githubusercontent.com/assets/172697/12008620/1654c29c-ac16-11e5-83a5-6319523ee73f.png">

Do you know what is wrong? Thank you!

**Comment by Krzysztof-Cieslak** [comment]
Please check if in `autocomplete-plus` package (built-in Atom package handling auto-complete API) you have checked "Show suggestion on keystroke" option. Otherwise it will only show completions when you use keybindings for `autocomplete-plus:activate` command

**Comment by palutz** [comment]
Also for me autocomplete is not working and the autocomplete-plus settings are ok.

PS: it looks like F# is not listed on the supported autocomplete provider. Could it be a problem?

**Comment by tpetricek** [comment]
Is this still unresolved? If so, I'll be happy to investigate...
