### ISSUE TITLE
'fsharpi' could not be spawned.

### ISSUE THREAD

**Issue by palutz** [ionide/ionide-fsharp#189]
Like mono, it looks like atom/ionide is having problem also on finding fsharpi
I'm getting this message when I try to open the fsi from atom
    'fsharpi' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

This is my situation:

    Mac OS X El Capitain 10.11.2
    
    palutz@Steo-MBP:~$ which fsharpi
    /usr/local/bin/fsharpi
    palutz@Steo-MBP:~$ which fsharpc
    /usr/local/bin/fsharpc
    palutz@Steo-MBP:~$ which mono
    /usr/local/bin/mono

    Fsharpc version
    F# Compiler for F# 4.0 (Open Source Edition)
    Freely distributed under the Apache 2.0 Open Source License

    palutz@Steo-MBP:~$ mono -V
    Mono JIT compiler version 4.2.1 (explicit/6dd2d0d Tue Nov 10 18:01:18 EST 2015)

**Comment by Krzysztof-Cieslak** [comment]
Path to `fsi` is defined in `ionide-fsi` plugin settings. Please check if right path is there.
