### ISSUE TITLE
Packages install but some features not working

### ISSUE THREAD

**Issue by StefanTihanyi** [ionide/ionide-fsharp#190]
I installed the packages using the ionide-installer. Some features work while others don't. The syntax highlighting and FSI panel work, but linting (error highlighting), type tooltips and autocompletion do not.

I am using Ubuntu 14.04. I initially was using Atom 1.3.3 but upgraded to 1.4.0, the problem occurred on both versions. I installed the packages using ionide-installer v1.3.0.

One more thing to note is that after playing around with settings, everything (linting, autocompletion, tooltips) was working at one point. The next time I opened atom it had reverted back to just the FSI/syntax highlighting working. I have not been able to recreate that success since then.

**Comment by Krzysztof-Cieslak** [comment]
Please open Developer Console (View |> Developer |> Toggle Developer Tools) and check if any errors are reported there.
