### ISSUE TITLE
"Queue" is not resolving

### ISSUE THREAD

**Issue by zarrini** [ionide/ionide-fsharp#209]
Hi,
I am using Visual Studio on Mac (El Capitan) and it seems "Queue" is not resolving, however when I run my program on Terminal, it works fine. I thought it could be a bug and wanted to share it:

    open System.Collections.Generic;;
    type ListTree<'a> = Node of 'a * (ListTree<'a> list)
    let bfIter f ltr =
        let todo = Queue<ListTree<'a>> ()
        todo.Enqueue ltr
        while(todo.Count <> 0) do
     let(Node(x,xs)) = todo.Dequeue()
            List.iter(todo.Enqueue) xs
            f x

OS X El Capitan (Version: 10.11.3) - Java Studio Code: Version 0.10.9 (0.10.9), ionide-fsharp 1.2.0

**Comment by lilred** [comment]
Minimal reproduction:

    let foo = System.Collections.Generic.Queue<int> ()

Shows red squigglies under `Queue`, and `Error: The value, constructor, namespace or type 'Queue' is not defined`. The code actually compiles and runs, though.

Same problem is observed on the following platforms:
- OS X El Capitan, Atom 1.5.4, ionide-fsharp 1.7.0
- OS X El Capitan, Visual Studio Code 0.10.9, ionide-fsharp 1.2.0, reproduced on my machine and @zarrini's
- Windows running VS Code (I don't have more information right now, this is based on the reports of a fellow student)

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `Ionide-fsharp 1.9.0`

**Comment by lilred** [comment]
FYI this issue persists.
