### ISSUE TITLE
"#time" is not resolving

### ISSUE THREAD

**Issue by zarrini** [ionide/ionide-fsharp#212]
It shows a red squiggles under `#time` and `Error: "This directive may only be used in F# script files. Either remove the directive, move this code to a script file or delimit the directive with"`

- OS X El Capitan, Atom 1.5.4, ionide-fsharp 1.7.0
- OS X El Capitan, Visual Studio Code 0.10.11, ionide-fsharp 1.2.0

**Comment by cloudRoutine** [comment]
if you update vscode to the latest version is it still an issue?

**Comment by zarrini** [comment]
@cloudRoutine Jared my VSC is the latest version (Visual Studio Code 0.10.11) and I still have the problem.
Also it runs and shows the timing tho, but I still think it shouldn't show the red squiggles under the `#time` and the error message. so I thought it must be a bug!

**Comment by cloudRoutine** [comment]
sorry I should have been more specific, I meant the ionide-vscode plugin, 1.4.1 is the latest version

**Comment by zarrini** [comment]
Just updated and still have the problem.

**Comment by Krzysztof-Cieslak** [comment]
Are you using `fsx` file?

**Comment by zarrini** [comment]
@Krzysztof-Cieslak no, .fs
