### ISSUE TITLE
F# using keyword is not highlighted

### ISSUE THREAD

**Issue by aeschli** [ionide/ionide-fsharp#213]
From https://github.com/Microsoft/vscode/issues/4408:

Steps to Reproduce:
1.Open an F# source/script file in VS Code
```
open System.IO

let writetofile2 filename obj =
    using (System.IO.File.CreateText(filename)) ( fun file1 ->
        file1.WriteLine("{0}", obj.ToString() )
    )

writetofile2 "abc2.txt" "The quick sly fox jumped over the lazy brown dog."
```
2.Set the language to  F#  
3.The  using  keyword is not syntax-highlighted

Problem is that `using (System.IO.File.CreateText(filename)) (` is all one single token.

**Comment by cloudRoutine** [comment]
[`using` is a function not a keyword](https://msdn.microsoft.com/en-us/library/ee370506(v=vs.140).aspx)

Syntax highlighting issues should be reported at https://github.com/ionide/ionide-fsgrammar/issues
