### ISSUE TITLE
Cannot run code with unicode symbols

### ISSUE THREAD

**Issue by tpetricek** [ionide/ionide-fsharp#217]
Given the following:

    type Brazil = HtmlProvider<"https://en.wikipedia.org/w/index.php?title=States_of_Brazil&oldid=702738616">
    let brazil = Brazil.GetSample()

When I `Alt+Enter` the following:

    let r = brazil.Tables.``List of Brazilian states``.Rows.[0]
    r.``Density (2014) (km²)``

I get:

> my.fsx(1,3): error FS0039: The field, constructor or member 'Density (2014) (km²)' is not defined

It does not like the unicode symbol for some reason.

Same issue with:

    let a = '²'

You get:

> error FS0010: Unexpected quote symbol in binding

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `ionide-fsi 1.1.3`

**Comment by tpetricek** [comment]
Fantastic, thanks!
