### ISSUE TITLE
Sorting files in project

### ISSUE THREAD

**Issue by asgerhallas** [ionide/ionide-fsharp#222]
I was wondering if there's way to order the files like in VS? Or if I'm supposed to edit the fsproj file directly? 

Cheers :)

**Comment by Krzysztof-Cieslak** [comment]
Edit `fsproj` file by hand or use something like [Forge](https://github.com/fsprojects/Forge)

**Comment by asgerhallas** [comment]
Thanks for the quick answer! May I ask if that's because it can't be done in Atom or if it's just not a priority (or maybe even not a feature that's desirable for you at all)?

I find it a little confusing that the files are not listed in dependency order in the tree view... but maybe I should just stop worrying... or stop relying that much on the tree view :)

**Comment by Krzysztof-Cieslak** [comment]
It can be done in Atom (well, everything can be done in Atom). But it wouldn't be convenient for users (i.e. it would be modification of core Atom part what would be bit annoying for general [non-fsharp] usage) so I'm not really planning to implement it.  

It is confusing, but not much we can do with it.
