### ISSUE TITLE
'/usr/bin/mono' could not be spawned.

### ISSUE THREAD

**Issue by alanrsoares** [ionide/ionide-fsharp#223]
Even though mono is globally accessible from the terminal, ionide can't find it.
It's actually under `/user/local/bin`. 
But even if I change the path for mono at `ionide-sharp/settings` I still get the same error.

```
'/usr/bin/mono' could not be spawned. 
Is it installed and on your path? 
If so please open an issue on the package spawning the process.
```

**Comment by Krzysztof-Cieslak** [comment]
Try also setting mono path in `ionide-paket` if you have it installed.
