### ISSUE TITLE
Text does not display properly in interactive window when using dark theme?

### ISSUE THREAD

**Issue by toadhats** [ionide/ionide-fsharp#224]
Sorry if I'm reporting this in the wrong place, but I just installed the iodide modules for Atom, and everything is working fine under the hood, but the text in the interactive window is showing as dark grey, which doesn't work too well when using a dark theme, and also every line has a white border. I had a look in the settings for a "dark mode" but didn't find one, but I also can't find anyone else reporting this issue. Is it me? Is it the theme I'm using (Atom Material)? Is there a way to get it to work via configuration? Sorry if any of these are stupid questions, I'm fairly new to Atom.

![Screenshot](http://s32.postimg.org/b36yw3b2d/Screen_Shot_2016_05_05_at_7_55_34_PM.png)

**Comment by mandest** [comment]
I've also seen this issue, specifically when using Atom Material UI theme.

**Comment by Krzysztof-Cieslak** [comment]
This should be fixed with `Ionide-fsi 2.0.0`
