### ISSUE TITLE
Atom Linter fails to find references in .fs files

### ISSUE THREAD

**Issue by blair55** [ionide/ionide-fsharp#226]
Following up on the Gitter chat as at least one more person has the same issue...

The Atom Linter can find references when working with ``.fsx`` files. The ``open`` keyword works as expected when referencing modules & namespaces following the use of ``#I``, ``#r`` & ``#load`` directives.

However, ``open`` does not work in ``.fs`` files. The Linter fails to detect neighbouring modules:

![fs-file-refs-2](https://cloud.githubusercontent.com/assets/702272/15210090/7d9d1d8c-182c-11e6-89d6-16e8078caa75.png)

Using: Windows 10 / Atom 1.7.3 / ionide-fsharp 1.8.1

**Comment by claruspeter** [comment]
I concur.  However, I have found that making a non-consequential change to the referencing file and re-saving _sometimes_ fixes this problem.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `Ionide-fsharp 1.9.0`
