### ISSUE TITLE
Error Highlighting, Tooltips, and Autocomplete not taking effect

### ISSUE THREAD

**Issue by lambdakris** [ionide/ionide-fsharp#230]
The Error Highlighting, Tooltips, and Autocomplete features are not working for me. 

- I am on a Win 10 machine. F# was installed as part of VS 2015. 
- I added "C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0" to the PATH variable. 
- Yeoman and fsharp-generator are installed.
- I am using Atom
- Problems presented on both the previous and current (1.9.0 released the 19th) versions of Ionide

When I open in Dev Mode I see the following

With devtools
<img width="960" alt="dev mode with devtools" src="https://cloud.githubusercontent.com/assets/15176003/15400066/23775408-1db8-11e6-92eb-bdcbc25205ed.png">

Without devtools
<img width="960" alt="dev mode" src="https://cloud.githubusercontent.com/assets/15176003/15400067/2378b550-1db8-11e6-8cd1-8243f9e7019d.png">

Full source code available at [https://github.com/lambdakris/DigitRecognizer](https://github.com/lambdakris/DigitRecognizer)

Let me know if I can provide any more information.

**Comment by Krzysztof-Cieslak** [comment]
Try to run Atom in normal mode, not in developer mode.

**Comment by lambdakris** [comment]
So in normal mode I get no Atom errors, however, the error highlighting, tooltips, and autocomplete don't take effect. 

Specifically, no red squiggles under an erroneous expression, neither base types nor custom types get highlighted, no tooltip with type signature when I hover over a name, and no autocomplete/suggestions when opening namespaces or module functions or class members.

<img width="358" alt="atom_2016-05-19_12-49-20" src="https://cloud.githubusercontent.com/assets/15176003/15402088/5f67b400-1dc0-11e6-805c-e92482bfaba6.png">

**Comment by Krzysztof-Cieslak** [comment]
Being in normal mode open DevTools and check if any errors are reported there.

**Comment by lambdakris** [comment]
Yes, there is one error.

> Failed to load resource: the server responded with a status of 500 (Internal Server Error)
> http://localhost:8302/parse

<img width="416" alt="atom_2016-05-19_13-26-43" src="https://cloud.githubusercontent.com/assets/15176003/15403134/7c575a02-1dc5-11e6-8969-13c4d4454d78.png">

**Comment by lambdakris** [comment]
I should mention, I've now verified that the problems I'm seeing are only in script (.fsx) files. At first I thought it was in source (.fs) files as well but I guess it just takes a couple of seconds for the features to take effect when you open a source file. 

In regards to the script files, after looking at some older issues that sounded similar, I went ahead and included the script file in the project file (.fsproj) under the <ItemGroup> for including files. I tried to include it as a <None /> item and restarted Atom but that did not make a difference, then just in case as a <Compile /> item and restarted Atom but that did not make a difference either.

**Comment by donamk** [comment]
I am suffering from exactly same problems like as @lambdakris mentioned
I also tried VS Code but no luck (Error Highlighting, Tooltips, and Autocomplete not working)

if you need, just mention I can also provide more logs.

**Comment by EmilBB** [comment]
Having same issue. No error highlighting, tooltips or autocomplete.

`FSI` and `Yeoman `works fine.

Running latest version of `generator-fsharp`, `atom `and `ionide-installer`.

**Comment by EmilBB** [comment]
Installing VS 2015 solved it for me.

**Comment by lambdakris** [comment]
@EmilBB, out of curiosity, what version of Windows are you using and does the highlighting, tooltips, and autocomplete work on .fsx files as well?

**Comment by EmilBB** [comment]
@lambdakris, Windows 10 - Microsoft Windows Version 1511 (OS Build 10586.318)

**Comment by lambdakris** [comment]
@Krzysztof-Cieslak in case this might help you pin point or rule out certain problems, here are some shots of my F# dir and my PATH env var with the path to the F# dir. I also tried to add the path to the Fsc.exe and Fsi.exe and FsiAnyCpu.exe files themselves (rather than than just the dir) separately and simultaneously but none of it worked to get highlighting, tooltips, and autocomplete to work on .fsx files.

F# dir
![image](https://cloud.githubusercontent.com/assets/15176003/15449196/db518c28-1f44-11e6-86b1-0a54b041e180.png)

Path to F# dir in PATH env var
<img width="959" alt="fsharp path" src="https://cloud.githubusercontent.com/assets/15176003/15449176/43029bce-1f44-11e6-95ec-94d57ded5490.png">

Also, is a particular version of Node.js required? I have 6.0.0 installed...

**Comment by Krzysztof-Cieslak** [comment]
Try installing https://www.microsoft.com/en-us/download/details.aspx?id=40760

**Comment by lambdakris** [comment]
@Krzysztof-Cieslak Installing Microsoft Build Tools 2013 did the trick. Give it a try @donamk.

**Comment by stevenranney** [comment]
Although this issue is closed, the solution provided by Krzystof-Cieslak worked for me as well.
