### ISSUE TITLE
Auto-complete showing wrong icon for methods

### ISSUE THREAD

**Issue by OverlyExcessive** [ionide/ionide-fsharp#236]
Running Windows 10, VS Code 1.1.1 and Ionide 1.8.2 I'm now getting the "literal" icon for methods. See picture below:

![newicons](https://cloud.githubusercontent.com/assets/346756/15606890/396bca2a-240f-11e6-89c7-a785a7cb9c45.png)

**Comment by OverlyExcessive** [comment]
Update - As of the latest version (1.2.0) the method icons are showing up as property icons instead.

**Comment by Krzysztof-Cieslak** [comment]
Well, we can assume it was problem on Code side ;)
