### ISSUE TITLE
Running/Debugging not working ?

### ISSUE THREAD

**Issue by mmc41** [ionide/ionide-fsharp#239]
1) I have installed VS code 1.1.1 with ionide. I can get fsharp syntax highlightning and fsi commands to execute but can not run or debug anything. Contrary to the ionide screenshots I do not have a ">" button in the left panel to run something and the debug button does not display anything (debug does not recognize any environments but node.js and VSCode extension points). 
2) There is no documentation of how to run or execute stuff on the ionide website. The intro only shows f# interactive (which I got working without problems).

**Comment by OverlyExcessive** [comment]
AFAIK Ionide doesn't support debugging out of the box. You'd have to wire up the FSC to the VSCode debugger manually if you wanted that to work. As far as running goes, you can install the Ionide FAKE extension and build the project using that.

**Comment by Krzysztof-Cieslak** [comment]
One more point to above. On OSX it's possible to get F# debugging using mono debugger extension.
