### ISSUE TITLE
Trace messages are in the way

### ISSUE THREAD

**Issue by halcwb** [ionide/ionide-fsharp#247]
When I write a Fake script, lambdas get to become more than 7 lines of code. However, when writing those lamdas, a Trace message pops up and covers the editor field and is constantly in the way.

How can I change these trace settings, and the popup should not remain.

**Comment by cloudRoutine** [comment]
is this from the linter?
you can disable it in the settings

![](http://i.imgur.com/qZp27Ep.png)

@halcwb  if this isn't it can you take a screenshot of the issue you're having?

**Comment by halcwb** [comment]
It's linter, thanks. I disabled the showup. P.s. Is ionide going to add a specific F# linter?

**Comment by cloudRoutine** [comment]
it's using this linter https://github.com/fsprojects/FSharpLint
