### ISSUE TITLE
UTF8 is not handled properly

### ISSUE THREAD

**Issue by rojepp** [ionide/ionide-fsharp#34]
This code yields compilation errors:

```fsharp
type Ärende = {
   ABool: bool
}
```
![screen shot 2015-05-08 at 09 46 10](https://cloud.githubusercontent.com/assets/445888/7532726/96d11e9c-f56a-11e4-9303-3f00e65d710b.png)

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `1.3.0`

**Comment by rojepp** [comment]
Awesome, thanks!
