### ISSUE TITLE
FAKE support

### ISSUE THREAD

**Issue by forki** [ionide/ionide-fsharp#41]
first of all:

![fake](https://cloud.githubusercontent.com/assets/57396/7615104/814974d6-f99b-11e4-8b6f-a08a4f370c8a.gif)

At the moment we analyze and run the build.cmd. This is unfortunate on Mac and Linux.
I think you should only analyze the build.fsx and run it directly via Fake.exe

**Comment by mcgee** [comment]
But who would run Paket to download FAKE package from NuGet? It could be another .fsx script, in this case it could be cross-platform.

**Comment by Krzysztof-Cieslak** [comment]
Actually, we analyze (and run) 1st found file with `.cmd` extension, not necessary called `build.cmd`. We could try to do the same for `.sh` file if we run on mono.

I still think running through `.cmd` / `.sh` is better solution since there are some steps which are usually put in there (downloading Paket for example)

**Comment by Krzysztof-Cieslak** [comment]
Also another question is organization - should it be part of F# plugin or should we put it in it's own plugin? It can be used not only with F# projects so maybe good idea would be putting it aside?

**Comment by forki** [comment]
I think it should be separate project and also work for C# solutions

**Comment by Krzysztof-Cieslak** [comment]
Yep, I can agree that separate project is best way of doing it. However, it would be cool to make some structure to make sharing common code between Paket.Atom, FSharp.Atom and FAKE.Atom easy. Any ideas?

**Comment by forki** [comment]
Use paket's github file sharing feature. It's perfectly suited for this.

**Comment by Krzysztof-Cieslak** [comment]
Well, but those shared files are not just dependencies - I can edit some shared files from point of view of each plugin. It should be rather some kind of link ( I can change file from all projects and change is reflected everywhere)(no idea if we can do sth like that with GitHub / Paket)

**Comment by forki** [comment]
No that's not possible and while I can understand the benefits I didn't
find a good solution for this yet. Git submodule never worked for us.

**Comment by CumpsD** [comment]
Some additional chat we had on the FAKE support:

```
cumpsd [20:36] 
just tried to run it on a ProjectScaffold created project, but it errors out, mentioning init.fsx is not found. Was wondering how it is supposed to work
I picked FAKE build from command pallette
and did enter
I'm guessing it somehow finds this: https://github.com/exira/iis-ops/blob/master/build.cmd#L16
and tries to execute it (when it shouldnt)
just trying to understand the intended use case :simple_smile:

k_cieslak [20:57] 
why do you have `init.fsx` in `build.cmd` file while FAKE script is named `build.fsx` ?

cumpsd [20:58] 
that's the way https://github.com/fsprojects/ProjectScaffold/blob/master/build.cmd is :smile:

GitHub
fsprojects/ProjectScaffold
ProjectScaffold - A prototypical .NET solution (file system layout and tooling), recommended by the F# Foundation.

cumpsd [20:58]
it has an IF arround it
they check if build.fsx exist
if it doesnt, they call init

k_cieslak [20:58] 
Damn

cumpsd [20:58] 
init.fsx sets up the project and removes itself afterwards

k_cieslak [20:59] 
can You just remove this whole `IF` from it :stuck_out_tongue_winking_eye:

cumpsd [20:59] 
same for the https://github.com/fsprojects/ProjectScaffold/blob/master/build.sh#L19

cumpsd [20:59]
yeah :smile: but but... user experience! :stuck_out_tongue_winking_eye:

k_cieslak [21:01] 
Well, I'm just RegEx'ing `build.cmd` and find file name, didn't think that there can be more than one, will try to handle it

cumpsd [21:02] 
hmmm
perhaps regexing for all matches, checking which ones exist on disk, and then finding all targets from all the existing ones
aka: lots of work to change :S
```

**Comment by Krzysztof-Cieslak** [comment]
Yep, I'll need to work on it (probably solution You've suggested in chat). It's on TODO list ;)

**Comment by Krzysztof-Cieslak** [comment]
Also, after watching @tpetricek talk (https://vimeo.com/130350091) - it would be cool to have some way of using long-running FAKE tasks, and cancelling them.

**Comment by tpetricek** [comment]
Oooh, if I could trigger some command in Atom to start `build Whatever` in the background, that would be pretty neat :-)

**Comment by Krzysztof-Cieslak** [comment]
@tpetricek Actually, You are able to do it right now, there is only a problem with cancellation of long running task (Usually it's something like press any key in command line and there is no smart way to do it yet). Just only way to cancel it cancel it is closing Atom or using Windows Task Manager (or something similar on other OS).

**Comment by tpetricek** [comment]
Hmm, then I can probably hack this together in my build script :-)

Certainly not perfect, but say `build start` creates a file `build.running` and waits until it is deleted - and then I can have `build stop` which deletes it... Can I see the output of the build script somewhere too? (I sometimes printed various things into the output for debugging in the talk... but I guess I can use F# Interactive now!)

**Comment by Krzysztof-Cieslak** [comment]
FAKE support released and moved to own plugin
