### ISSUE TITLE
FSI REPL

### ISSUE THREAD

**Issue by cloudRoutine** [ionide/ionide-fsharp#75]
- [ ] REPL window input prompt
- [ ] REPL Input History
- [ ] Render HTML in panel

**Comment by abjrcode** [comment]
Is someone working on this ?
I might be interested in implementing this piece of functionality.

**Comment by flq** [comment]
I am pretty confused about the fsi functionality...how is the fsi supposed to work inside Atom. I am on 0.8.2 on OSX. Calling fsi: open I get a window into which I can't type anything. Calling send file bails out with an error which, however, seemed related to a different package.

**Comment by Krzysztof-Cieslak** [comment]
@flq: FSI panel is readonly be design. Only way to send code to FSI is by using Send Line / Selection / FIle commands. If using those commands result in errors, please report it in separate issue. I'll try to help having bit more details :)

**Comment by andregsilv** [comment]
I would like to be able to type in the REPL
